### ISSUE TITLE
Player sprite sized wrong

### ISSUE THREAD

**Issue by CheeseLord** [CheeseLord/plaid#25]
Blitting the sprite doesn't scale it appropriately.  We need to handle that.

**Comment by CheeseLord** [comment]
We rescale every frame, and we flatten at the edges of the world.  Both should be fixed.

**Comment by CheeseLord** [comment]
Also, sometimes the sprite overlaps the platforms a little.  We can probably fix this with alpha or drawing the platforms on top.

**Comment by kronmillerg** [comment]
The fact that things sometimes overlap by a pixel is not an issue with the player being sized wrong; it probably has to do with imprecisions when scaling from world to screen coordinates. If it's a problem, we should file a separate issue for it. I will close this issue once the edge-of-world flattening bug is fixed.
