### ISSUE TITLE
Remove all use of floating point?

### ISSUE THREAD

**Issue by kronmillerg** [CheeseLord/plaid#8]
I think we can probably do all of our math using integers (longs), if we choose the units to be tiny enough. This might remove precision problems associated with using floating-point. It'll also probably be faster. That said, we haven't observed precision problems yet, and we're not having trouble with performance, so this is not urgent.

**Comment by CheeseLord** [comment]
There doesn't seem to be much reason to do this, and dealing with units is a huge hassle if we don't have to.
